spark.authenticate = true
spark.authenticate.secret = test
spark.network.crypto.enabled = true
spark.hadoop.fs.hdfs.impl = org.apache.hadoop.hdfs.DistributedFileSystem
spark.hadoop.fs.file.impl = org.apache.hadoop.fs.LocalFileSystem
spark.jars.packages = org.apache.hadoop:hadoop-aws:3.3.2,com.amazonaws:aws-java-sdk-bundle:1.12.262
spark.hadoop.fs.s3a.impl = org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.aws.credentials.provider = org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.access.key = changeme
spark.hadoop.fs.s3a.secret.key = changeme
spark.hadoop.fs.s3a.endpoint = minio:9000
spark.hadoop.fs.s3a.path.style.access = true
spark.hadoop.fs.s3a.fast.upload = true
