limit.maxIDLength:
  - value: 255
    constraints: {}
system.forceSearchAttributesCacheRefreshOnRead:
  - value: false
    constraints: {}
limit.historyCount.error:
  - value: 2147483647
    constraints: {}
