services:
    bucket:
        ports:
            - "9000:9000"
            - "9001:9001"

    mongo:
        ports:
            - "27017:27017"

#    scylla-master:
#        command: ["--smp=4", "--memory=2G", "--overprovisioned=1"]
#        ports:
#            - "9042:9042"
#
#    scylla-seed-1:
#        profiles:
#            - "donotstart"
#
#    scylla-seed-2:
#        profiles:
#            - "donotstart"

    temporal:
        ports:
            - "7233:7233"

    temporal_ui:
        ports:
            - "8080:8080"

    app_repacker:
        profiles:
            - "donotstart"

    app_calculator:
        profiles:
            - "donotstart"

    spark-master:
        profiles:
            - "donotstart"

    spark-worker:
        profiles:
            - "donotstart"

    livy:
        profiles:
            - "donotstart"

    jupyter:
        profiles:
            - "donotstart"
