services:
    spark-master:
        build:
            context: ..
            dockerfile: infrastructure/spark.Dockerfile
        expose:
            - "8080"
            - "7077"
        environment:
            - SPARK_MODE=master
            - SPARK_MASTER_HOST=spark-master
            - SPARK_RPC_AUTHENTICATION_ENABLED=${SPARK_RPC_AUTHENTICATION_ENABLED}
            - SPARK_RPC_AUTHENTICATION_SECRET=${SPARK_RPC_AUTHENTICATION_SECRET}
            - SPARK_RPC_ENCRYPTION=${SPARK_RPC_ENCRYPTION}
            - SPARK_LOCAL_STORAGE_ENCRYPTION=${SPARK_LOCAL_STORAGE_ENCRYPTION}
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
            interval: 10s
            timeout: 10s
            retries: 5
        networks:
            - enhancer3d-network

    spark-worker:
        build:
            context: ..
            dockerfile: infrastructure/spark.Dockerfile
        expose:
            - "8081"
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER=spark://spark-master:7077
            - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
            - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
            - SPARK_RPC_AUTHENTICATION_ENABLED=${SPARK_RPC_AUTHENTICATION_ENABLED}
            - SPARK_RPC_AUTHENTICATION_SECRET=${SPARK_RPC_AUTHENTICATION_SECRET}
            - SPARK_RPC_ENCRYPTION=${SPARK_RPC_ENCRYPTION}
            - SPARK_LOCAL_STORAGE_ENCRYPTION=${SPARK_LOCAL_STORAGE_ENCRYPTION}
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8081" ]
            interval: 10s
            timeout: 10s
            retries: 5
        depends_on:
            - spark-master
        networks:
            - enhancer3d-network

    livy:
        container_name: livy
        build:
            context: ..
            dockerfile: infrastructure/livy.Dockerfile
        volumes:
            - ./config/livy/spark_defaults.conf:/opt/livy/conf/spark-defaults.conf
            - ../:/work
        depends_on:
            - spark-master
        networks:
            - enhancer3d-network

    jupyter:
        container_name: jupyter
        build:
            context: ..
            dockerfile: infrastructure/jupyter.Dockerfile
        depends_on:
            - spark-master
            - livy
        environment:
            - JUPYTER_ENABLE_LAB=yes
            - JUPYTER_TOKEN=${JUPYTER_TOKEN}
        volumes:
            - ../:/home/jovyan/work
        networks:
            - enhancer3d-network
