services:
    bucket:
        ports:
            - "9000:9000"
            - "9001:9001"

    mongo:
        ports:
            - "27017:27017"

    temporal:
        ports:
            - "7233:7233"

    temporal_ui:
        ports:
            - "8080:8080"

    app_repacker:
        develop:
            watch:
                -   action: rebuild
                    path: ../src
                    target: /app/src
                -   action: rebuild
                    path: ../requirements.txt
        restart: no

    app_calculator:
        develop:
            watch:
                -   action: rebuild
                    path: ../src
                    target: /app/src
                -   action: rebuild
                    path: ../requirements.txt
        restart: no

    spark-master:
        ports:
            - "8081:8080"
            - "7077:7077"

    spark-worker:
        ports:
            - "8082:8081"

    jupyter:
        ports:
            - "8888:8888"
