services:
    bucket:
        ports:
            - "9001:9001"

#    mongo:
#        deploy:
#            resources:
#                limits:
#                    memory: 16g
#        ulimits:
#            nofile:
#                soft: 64000
#                hard: 64000
#            nproc: 64000

    temporal_ui:
        ports:
            - "8080:8080"

    app_repacker:
        scale: ${APP_REPACKER_SCALE}

    app_calculator:
        scale: ${APP_CALCULATOR_SCALE}

    spark-master:
        ports:
            - "8081:8080"
            - "7077:7077"

    spark-worker:
        scale: ${SPARK_WORKER_SCALE}

    jupyter:
        ports:
            - "8888:8888"

    livy:
        ports:
            - "4040:4040"

