services:
    bucket:
        ports:
            - "9001:9001"

    temporal_ui:
        ports:
            - "8080:8080"

    app_repacker:
        scale: 1

    app_calculator:
        scale: 1

    spark-master:
        ports:
            - "8081:8080"
            - "7077:7077"

    jupyter:
        ports:
            - "8888:8888"
